
services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud 
    restart: no
    ports:
      - 8001:80
    volumes:
      - nextcloud:/var/www/html
    networks:
      homelab-network:

networks:
  homelab-network:
    external: true

volumes:
  nextcloud:
