
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: localhost:8008
      PUID: 1000
      PGID: 1000
    ports:
      - "8008:3000"
    volumes:
      - homepage_data:/app/config

networks:
  homelab-network:
    external: true

volumes:
  homepage_data:

